### ISSUE TITLE
ETA on a new release?

### ISSUE THREAD

**Issue by geoffjukes** [onefinestay/nameko-sqlalchemy#19]
Hi @mattbennett 

You've gone and done it again.... You've added something that solves a problem I was having! But it's not in the PyPi release.

Do you know when you might be able to cut a new release that includes the `transaction_retry` code?

Many thanks,

Geoff

**Comment by mattbennett** [comment]
Sorry for the delay. Actually this feature was all @vmikki's contribution :) I'll cut a release shortly

**Comment by mattbennett** [comment]
It's out 😄

**Comment by geoffjukes** [comment]
Woohoo! Thanks @mattbennett 👍
