### ISSUE TITLE
A way to supply create_engine kwargs through config (pool size)

### ISSUE THREAD

**Issue by alexeysofin** [onefinestay/nameko-sqlalchemy#21]
Currently there is not way to supply connection pool size. And if max_workers is larger that default 
pool_size+max_overflow we get

`QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30 (Background on this error at: http://sqlalche.me/e/3o7r)
`

as a result

**Comment by mattbennett** [comment]
There are two competing PRs that add this. I will prompt the contributors

**Comment by alexeysofin** [comment]
@mattbennett thank you, should I close this one?

**Comment by mattbennett** [comment]
I think leave it open. We can close it when one of the PRs actually lands :)

**Comment by mattbennett** [comment]
@alexeysofin note that this particular "QueuePool limit reached" error probably happens more with the original `DatabaseSession` DP than the newer `Database` DP. I've added some notes about the differences to the README. 

If you have concurrent workers that don't actually use the database you might be able to avoid the error by switching to the newer DP.

**Comment by alexeysofin** [comment]
@mattbennett thank you, the new interface with context manager is certainly better, but the problem is that we have all event handlers that do nothing except for reading/writing to database, so in the worst case max_workers will still exceed the pool size.

**Comment by mattbennett** [comment]
Added in #17
