### ISSUE TITLE
How do I create tables with this? 

### ISSUE THREAD

**Issue by rollokb** [onefinestay/nameko-sqlalchemy#5]
The example given in the readme doesn't create new tables and so will error out.

This is my test

-----

```

from nameko.rpc import rpc
from nameko_sqlalchemy import DatabaseSession

from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Integer, String


DeclBase = declarative_base(name='testbase')

class ExampleModel(DeclBase):
    __tablename__ = 'example'
    id = Column(Integer, primary_key=True)
    data = Column(String)

class ExampleService(object):
    name = "example_service"
    session = DatabaseSession(DeclBase)

    @rpc
    def init_service(self, name):
        obj = ExampleModel(data=name)
        self.session.add(obj)
        self.session.commit()
        return "Hello, {}!".format(name)


```

When launching using `nameko run service --config=service.yaml` and sending a message it just errors 

```
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: example [SQL: 'INSERT INTO ex│ 11     data = Column(String)
```

So how do I create the tables?

**Comment by mattbennett** [comment]
Creation of the tables is outside the scope of running a nameko service, the same way django's `manage.py runserver` will throw an error if you've not created the database prior.

You can do it any way that makes sense for your application. The tests for nameko-sqlalchemy do it with the declarative base (https://github.com/onefinestay/nameko-sqlalchemy/blob/master/test/test_nameko_sqlalchemy.py#L135). You might prefer to use a migration toolkit like [alembic](https://pypi.python.org/pypi/alembic) or [sqlalchemy-migrate](https://sqlalchemy-migrate.readthedocs.io/en/latest/).

**Comment by rollokb** [comment]
Sorry to turn this into my own personal support thread (down to my poor knowledge of SQLAlchemy)

But in the existing ExampleModel how would I get the current SQLAlchemy session, in the ExampleModel? Do I have to pass the session into the class?

**Comment by mattbennett** [comment]
I'm not sure I understand the question. Models are declarative -- they're not really aware of sessions.

If you have a model instance that is bound to a session, but you somehow don't have a reference to that session, you can use [object_session](http://docs.sqlalchemy.org/en/latest/orm/session_api.html#sqlalchemy.orm.session.object_session) to get it, but in the context of nameko I'm not sure how you'd end up in that situation.

What are you trying to achieve?

**Comment by rollokb** [comment]
This is my fault, I was creating an in memory SQLite database, which in a multiprocess model was pointless.
